# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: exec
    main: ./cmd/prom-to-apt-dater
    binary: prom-to-apt-dater
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X "github.com/webhippie/prom-to-apt-dater/pkg/version.String={{.Version}}" -X "github.com/webhippie/prom-to-apt-dater/pkg/version.Revision={{.Commit}}" -X "github.com/webhippie/prom-to-apt-dater/pkg/version.Date={{.Date}}"
    tags:
      - netgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm

archives:
  - id: exec
    ids:
      - exec
    name_template: "prom-to-apt-dater-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - CHANGELOG.md
      - src: cmd/prom-to-apt-dater/README.md
        dst: README.md

nfpms:
  - id: exec
    ids:
      - exec
    package_name: prom-to-apt-dater
    file_name_template: "prom-to-apt-dater-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    vendor: Webhippie
    homepage: https://webhippie.github.io/prom-to-apt-dater/
    maintainer: Thomas Boerger <thomas@webhippie.de>
    description: |-
      Prometheus targets for APT-Dater
    license: Apache 2.0
    formats:
      - deb
      - rpm

signs:
  - id: archives
    signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: archive
    args:
      - --batch
      - --armor
      - --local-user
      - 552D1DF54CBEA471C570C816EA4B5799921648E8
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
  - id: packages
    signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: package
    args:
      - --batch
      - --armor
      - --local-user
      - 552D1DF54CBEA471C570C816EA4B5799921648E8
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

snapshot:
  version_template: testing

changelog:
  disable: true

checksum:
  disable: false
  split: true
