FROM webhippie/alpine:arm64v8

RUN apk update && \
	apk upgrade && \
	rm -rf /var/cache/apk/*

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Prometheus to APT-Dater" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/prom-to-apt-dater"]
CMD ["generate"]

COPY bin/prom-to-apt-dater /usr/bin/prom-to-apt-dater
