FROM amd64/alpine:3.18@sha256:d695c3de6fcd8cfe3a6222b0358425d40adfd129a8a47c3416faff1a8aece389 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

ENTRYPOINT ["/usr/bin/prom-to-apt-dater"]
CMD ["generate"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/prom-to-apt-dater /usr/bin/prom-to-apt-dater
