FROM i386/alpine:3.22@sha256:d82a85e22ec68fbe569507f2357edac47621e4b87c4397a08339f8cae93c5e2b AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

ENTRYPOINT ["/usr/bin/prom-to-apt-dater"]
CMD ["generate"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/prom-to-apt-dater /usr/bin/prom-to-apt-dater
