---
output:
  filter:
  group: job
  name: '[__address__]'
  user: static("root")
  host: '[__address__]'
  port: static("22")
  file:
  template:

prometheus:
  url: http://localhost:9090
  username:
  password:

log:
  level: info
  pretty: true
  color: true

...
